### ISSUE TITLE
Add build dependencies

### ISSUE THREAD

**Issue by leechuck** [bio-ontology-research-group/mowl#19]
It would be good if the "build from github" could list the build dependencies necessary to get the build (JVM, python version, gradle, etc.). At the moment, users installing from source need to figure out what to install.

**Comment by leechuck** [comment]
Also, building from source seems to require grade version >6. Would be good to add this as dependency (in particular as it's not standard on my GNU/Linux distribution).

**Comment by leechuck** [comment]
Should also add matplotlib to dependencies to be able to visualize embeddings (as in the tutorials)

**Comment by ferzcam** [comment]
> Also, building from source seems to require gradle version >6. Would be good to add this as dependency (in particular as it's not standard on my GNU/Linux distribution).

To solve this issue you need to follow the "Building from source" script. In that scritp, the conda environment creation is done using the file `environment.yml` which contains `gradle` as conda dependency and imports automatically. It is not needed to install Gradle by yourself.
