### ISSUE TITLE
Customized random walks

### ISSUE THREAD

**Issue by azzatha** [bio-ontology-research-group/mowl#25]
Greetings, 

Thank you for the nice tool! 

I wonder if it's possible to customize the walks by including only the walks for specific entities? it could be an input file with the entities that we need to generate the embeddings for them. I think this might be more time/space-efficient, rather than generating representations for all the entities/classes.

Best,

**Comment by ferzcam** [comment]
Hi, thank you for your suggestion. This feature is expected to be ready in v0.1.0. However, we have a pre-release [v0.1.0-alpha](https://github.com/bio-ontology-research-group/mowl/releases/tag/v0.1.0) which you can try installing by:
```
pip install https://github.com/bio-ontology-research-group/mowl/releases/download/v0.1.0/mowl_borg-0.1.0-py3-none-any.whl
```
Documentation of how to use it is at [mOWL docs](https://mowl.readthedocs.io/en/latest/random_walks/index.html).
