### ISSUE TITLE
Is there any way to run generate embeddings from my corpus ,not the built-in dataset?

### ISSUE THREAD

**Issue by CNwangbin** [bio-ontology-research-group/mowl#27]
I want to use my data as corpus.

**Comment by ferzcam** [comment]
Hi, you can bring your own `.owl` files and turn them into mOWL datasets using:
```
from mowl.datasets.base import PathDataset
ds = PathDataset("training_ontology.owl", "validation_ontology.owl", "testing_ontology.owl")
```
The validation and testing owl files are optional.
For more details on how to add information to an ontology please refer to this [example](https://mowl.readthedocs.io/en/v0.1.0/tutorials/dataset.html#adding-annotations-to-ontologies).

**Comment by CNwangbin** [comment]
Yes, thanks. I found that.
&nbsp;
&nbsp;
------------------&nbsp;Original&nbsp;------------------
From: "Fernando&nbsp;Zhapa"; 
Date: 2022年9月17日(星期六) 晚上7:28
To: "bio-ontology-research-group/mowl"; 
Cc: ***@***.***>; "Author"; 
Subject: Re: [bio-ontology-research-group/mowl] Is there any way to run generate embeddings from my corpus ,not the built-in dataset? (Issue #27)

&nbsp;


 
Hi, you can bring your own .owl files and turn them into mOWL datasets using:
 from mowl.datasets.base import PathDataset ds = PathDataset("training_ontology.owl", "validation_ontology.owl", "testing_ontology.owl")  
The validation and testing owl files are optional.
 For more details on how to add information to an ontology please refer to this example.

**Comment by CNwangbin** [comment]
I have a new question. After training, I got a embeddings generator which corresponding to a certain class. My
&nbsp;question is "how to get the&nbsp;correct classes order&nbsp; for the embeddings generator" .
&nbsp;
------------------&nbsp;Original&nbsp;------------------
From: ***@***.***&gt;;
Date: &nbsp;Sat, Sep 17, 2022 07:28 PM
To: ***@***.***&gt;; 
Cc: ***@***.***&gt;; ***@***.***&gt;; 
Subject: &nbsp;Re: [bio-ontology-research-group/mowl] Is there any way to run generate embeddings from my corpus ,not the built-in dataset? (Issue #27)

&nbsp;



 
Hi, you can bring your own .owl files and turn them into mOWL datasets using:
 from mowl.datasets.base import PathDataset ds = PathDataset("training_ontology.owl", "validation_ontology.owl", "testing_ontology.owl")  
The validation and testing owl files are optional.
 For more details on how to add information to an ontology please refer to this example.

**Comment by ferzcam** [comment]
The embeddings contents is usually a dictionary of the form `class name -> embedding vector`. This would apply for methods such as Word2Vec. Are you using that one or other different?

**Comment by CNwangbin** [comment]
Yes,I found that in tutorial examples. The new question is how to find classes order corresponding to embedding generator order.

&nbsp;
&nbsp;
------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Fernando&nbsp;Zhapa"; 
发送时间: 2022年9月17日(星期六) 晚上8:33
收件人: "bio-ontology-research-group/mowl"; 
抄送: ***@***.***>; "Author"; 
主题: Re: [bio-ontology-research-group/mowl] Is there any way to run generate embeddings from my corpus ,not the built-in dataset? (Issue #27)

&nbsp;



 
The embeddings contents is usually a dictionary of the form class name -&gt; embedding vector. This would apply for methods such as Word2Vec. Are you using that one or other different?
 
&mdash;

**Comment by ferzcam** [comment]
You can access the classes in the dataset doing:
```
dataset = # Assume this is a mowl dataset
classes  = dataset.classes.as_str
```
That is a list of classes from which you can generate a dictionary:
```
class_to_id = {v:k for k,v in enumerate(classes)}
```
Please let me know if this helps.

**Comment by CNwangbin** [comment]
Yes, thx. But there are some question remain here. The number of classes should equal to the number of vectors. Is there any other misstake?
![image](https://user-images.githubusercontent.com/87804802/190960457-9d4741f5-dfab-428a-a650-d00ba4a090be.png)

**Comment by CNwangbin** [comment]
``

> Yes, thx. But there are some question remain here. The number of classes should equal to the number of vectors. Is there any other misstake? ![image](https://user-images.githubusercontent.com/87804802/190960457-9d4741f5-dfab-428a-a650-d00ba4a090be.png)

this is my code.
`import mowl
mowl.init_jvm("4g")
from mowl.datasets.base import PathDataset

ds = PathDataset("go.owl")
from mowl.projection.dl2vec.model import DL2VecProjector
projector = DL2VecProjector(bidirectional_taxonomy = True)
edges = projector.project(ds.ontology)
from mowl.walking.factory import walker_factory
walker = walker_factory("deepwalk", alpha = 0.1, walk_length = 10, num_walks = 10, outfile = "data/walks/walk.txt")
walker.walk(edges)
from gensim.models import Word2Vec
from gensim.models.word2vec import LineSentence


corpus = LineSentence(walker.outfile)

w2v_model = Word2Vec(
       corpus,
       sg=1,
       min_count=1,
       vector_size=10,
       window = 10,
       epochs = 10,
       workers = 16)





`

**Comment by ferzcam** [comment]
There is no mistake, but there are classes in the ontology that are not being captured by the projection method (DL2VecProjector) because those classes are obsolete, deprecated or are part of axioms that cannot be processed by the projection method.

As an example check `http://purl.obolibrary.org/obo/GO_1901916`
That is part of `ds.classes.as_str` but not part of `w2v_model.wv` (I tried with the last version of GO at this time) and appears as OBSOLETE in the `go.owl` file.

Considering obsolete classes in the function `dataset.classes.as_str` will be considered a bug and will be fixed in future versions. 

If you need further help, please let us know. Thanks.

**Comment by ferzcam** [comment]
Since you are working with Gensim's Word2Vec model, would `w2v_model.wv.key_to_index` work?

**Comment by CNwangbin** [comment]
thanks you, ferzcam. It works well. And is that right way to get (class, vector) pairs?

![image](https://user-images.githubusercontent.com/87804802/190979237-d2404954-bfad-42f2-9b7c-52e67f30efc7.png)

**Comment by ferzcam** [comment]
I think that is right. There is also this way:
```
for class in w2v_model.wv.index_to_key:
    vector = in w2v_model.wv[class]
    print(class)
    print(vector)
```

**Comment by CNwangbin** [comment]
OK, that is good.
