### ISSUE TITLE
Implement Inductive training 

### ISSUE THREAD

**Issue by azzatha** [bio-ontology-research-group/mowl#43]

**Comment by ferzcam** [comment]
I checked the commit. I think the `test_dl2vec` file is not run since it does not inherit from `unittest.TestCase`.

**Comment by ferzcam** [comment]
I added the `model.add_axioms` method. It does several things:
- Adds the axioms into the training ontology of the dataset in the model.
- The entities are ordered alphabetically, Therefore the method also reindexes the dataset classes, relations and individuals
- Reindexes the embeddings of classes, relations and individuals in the current model and for the new entities, random embeddings are assigned.
I tested this method with `EmbeddingELModels`. Testing with `GraphModel` is missing.

**Comment by ferzcam** [comment]
Method `add_axioms` works now for Graph Models with Random Walks. 
Next step: Implement for Graph Models with KGE.

**Comment by ferzcam** [comment]
Next Step: Syntatic Models
