### ISSUE TITLE
issues with installation

### ISSUE THREAD

**Issue by chestnzu** [bio-ontology-research-group/mowl#54]
Hi there:
          I meet some issues with the package installation. Following the documentations I install everything that was mentioned in https://mowl.readthedocs.io/en/latest/install/index.html.  When I tried to run the embedding methods provided at this page 'https://mowl.readthedocs.io/en/latest/graphs/kge.html' I got this error. 
![image](https://github.com/bio-ontology-research-group/mowl/assets/40864288/17892f22-0538-460c-9729-dea8c0769000)

I tried to install from pypi and build from source code, but it still didn't work. Can you help me to figure out what is the issue? Thank you in advance!

**Comment by ferzcam** [comment]
Hi. Do you have JDK installed? Which version of JDK are you using?

**Comment by chestnzu** [comment]
> 

Hi ferzcam:
   Thank you for replying so quick! I do have JDK installed. the version of JDK in my ubuntu is JDK8 
  
![image](https://github.com/bio-ontology-research-group/mowl/assets/40864288/b7bd2a04-24fe-4b65-b068-2a19c6a24590)

**Comment by ferzcam** [comment]
You are welcome! Would you please share the version of mowl that was installed from pip and also the script you are trying to run so I can try to reproduce the error?

**Comment by chestnzu** [comment]
> You are welcome! Would you please share the version of mowl that was installed from pip and also the script you are trying to run so I can try to reproduce the error?

Sure! the version of mowl I installed is the latest one (I downloaded from github). I was trying to run the code:
import jpype
jpype.startJVM(jpype.getDefaultJVMPath())
from mowl.projection.edge import Edge
from mowl.datasets.builtin import PPIYeastSlimDataset
from mowl.projection import TaxonomyProjector

# ds = PPIYeastSlimDataset()
# proj = TaxonomyProjector(True)

edges = proj.project(ds.ontology)


and I get 
![image](https://github.com/bio-ontology-research-group/mowl/assets/40864288/25b007f2-d007-4c71-a6cd-457315a71266)

**Comment by ferzcam** [comment]
I think the problem is the way the JVM is being started. Would you please replace: 
```
import jpype
jpype.startJVM(jpype.getDefaultJVMPath())
```
by
```
import mowl
mowl.init_jvm("2g") # fell free to assign the memory you wish
```
The JVM initialization will be done by mOWL and load all the JAR files. If you initialize the JVM from JPype the necessary JAR files will not be loaded.

Also, if you install from source code please make sure to install the commit of the last release since the current commit might contain undocumented new code. 

Please let me know if that solves the error.

**Comment by chestnzu** [comment]
> I think the problem is the way the JVM is being started. Would you please replace:
> 
> ```
> import jpype
> jpype.startJVM(jpype.getDefaultJVMPath())
> ```
> 
> by
> 
> ```
> import mowl
> mowl.init_jvm("2g") # feel free to assign the memory you wish
> ```
> 
> The JVM initialization will be done by mOWL and load all the JAR files. If you initialize the JVM from JPype the necessary JAR files will not be loaded.
> 
> Also, if you install from source code please make sure to install the commit of the last release since the current commit might contain undocumented new code.
> 
> Please let me know if that solves the error.

Thank you! I will have a try tomorrow morning. (A little bit late right now :D)
Hope you have a great day!

**Comment by chestnzu** [comment]
> I think the problem is the way the JVM is being started. Would you please replace:
> 
> ```
> import jpype
> jpype.startJVM(jpype.getDefaultJVMPath())
> ```
> 
> by
> 
> ```
> import mowl
> mowl.init_jvm("2g") # feel free to assign the memory you wish
> ```
> 
> The JVM initialization will be done by mOWL and load all the JAR files. If you initialize the JVM from JPype the necessary JAR files will not be loaded.
> 
> Also, if you install from source code please make sure to install the commit of the last release since the current commit might contain undocumented new code.
> 
> Please let me know if that solves the error.

It works! Thanks a lot.
