### ISSUE TITLE
A bug that may be due to a mismatch between version of the code and documentation

### ISSUE THREAD

**Issue by CNwangbin** [bio-ontology-research-group/mowl#60]
### Describe the bug

1. I installed mowl package(version=0.2.0).
2. I ran the example code in documentation [link](https://mowl.readthedocs.io/en/latest/graphs/kge.html#generating-embeddings-using-a-mowl-model).
3. I got a Module Not Found Error in the last of link tutorial code block. 

> ModuleNotFoundError                       Traceback (most recent call last)
/home/wangbin/contrast_exp/TransH/transh_cafa3.ipynb Cell 4 in 5
      [1](vscode-notebook-cell://ssh-remote%2Blabx-compute/home/wangbin/contrast_exp/TransH/transh_cafa3.ipynb#W3sdnNjb2RlLXJlbW90ZQ%3D%3D?line=0) # from mowl.models.graph_kge.graph_pykeen_model import GraphPlusPyKEENModel
      [4](vscode-notebook-cell://ssh-remote%2Blabx-compute/home/wangbin/contrast_exp/TransH/transh_cafa3.ipynb#W3sdnNjb2RlLXJlbW90ZQ%3D%3D?line=3) from mowl.datasets.builtin import FamilyDataset
----> [5](vscode-notebook-cell://ssh-remote%2Blabx-compute/home/wangbin/contrast_exp/TransH/transh_cafa3.ipynb#W3sdnNjb2RlLXJlbW90ZQ%3D%3D?line=4) from mowl.models import GraphPlusPyKEENModel
      [6](vscode-notebook-cell://ssh-remote%2Blabx-compute/home/wangbin/contrast_exp/TransH/transh_cafa3.ipynb#W3sdnNjb2RlLXJlbW90ZQ%3D%3D?line=5) from mowl.projection import DL2VecProjector
      [7](vscode-notebook-cell://ssh-remote%2Blabx-compute/home/wangbin/contrast_exp/TransH/transh_cafa3.ipynb#W3sdnNjb2RlLXJlbW90ZQ%3D%3D?line=6) from pykeen.models import TransE
File /home/software/anaconda3/envs/mowl/lib/python3.8/site-packages/mowl/models/__init__.py:3
      1 from mowl.models.elembeddings.model import ELEmbeddings
      2 from mowl.models.elboxembeddings.model import ELBoxEmbeddings
----> 3 from mowl.models.graph_random_walk.random_walk_w2v_model import RandomWalkPlusW2VModel
      4 from mowl.models.graph_kge.graph_pykeen_model import GraphPlusPyKEENModel
      5 from mowl.models.syntactic.w2v_model import SyntacticPlusW2VModel
ModuleNotFoundError: No module named 'mowl.models.graph_random_walk'

### How to reproduce

# This is the code I exactly ran.

`
import mowl
mowl.init_jvm("20g")
from mowl.projection.edge import Edge
from mowl.datasets.builtin import PPIYeastSlimDataset
from mowl.projection import TaxonomyProjector

ds = PPIYeastSlimDataset()
proj = TaxonomyProjector(True)

edges = proj.project(ds.ontology)

#edges = [Edge("node1", "rel1", "node3"), Edge("node5", "rel2", "node1"), Edge("node2", "rel1", "node1")] # example of edges
triples_factory = Edge.as_pykeen(edges, create_inverse_triples = True)

from pykeen.models import TransE
pk_model = TransE(triples_factory=triples_factory, embedding_dim = 50, random_seed=42)

from mowl.kge import KGEModel

model = KGEModel(triples_factory, pk_model, epochs = 10, batch_size = 32)
model.train()
ent_embs = model.class_embeddings_dict
rel_embs = model.object_property_embeddings_dict

from mowl.datasets.builtin import FamilyDataset
from mowl.models import GraphPlusPyKEENModel
from mowl.projection import DL2VecProjector
from pykeen.models import TransE
import torch as th

model = GraphPlusPyKEENModel(FamilyDataset())
model.set_projector(DL2VecProjector())
model.set_kge_method(TransE, random_seed=42)
model.optimizer = th.optim.Adam
model.lr = 0.001
model.batch_size = 32
model.train(epochs = 2)

# Get embeddings

class_embs = model.class_embeddings
role_embs = model.object_property_embeddings
ind_embs = model.individual_embeddings
`

### Environment

# OS information

> NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"
CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

# Python version

> Python=3.8.13

# mOWL version

> mowl-borg==0.2.0

# JDK version

> openjdk 17.0.3-internal 2022-04-19

### Additional information

The main reason is this code.
![image](https://github.com/bio-ontology-research-group/mowl/assets/87804802/76f4b9b5-5eaf-4ab0-9478-edaf26335fe7)

**Comment by ferzcam** [comment]
Hi. Thanks for pointing out this bug. It seems there were some missing `__init__.py` files in some modules and this was not caught in the testing phase. I have added the files and released a patch version so you can install as `pip install mowl-borg==0.2.1`. Please let me know if this works for you. Thanks :)

**Comment by CNwangbin** [comment]
> Hi. Thanks for pointing out this bug. It seems there were some missing `__init__.py` files in some modules and this was not caught in the testing phase. I have added the files and released a patch version so you can install as `pip install mowl-borg==0.2.1`. Please let me know if this works for you. Thanks :)

Thanks. It fixed the bug.
