### ISSUE TITLE
Import ELEModule error

### ISSUE THREAD

**Issue by Mhaller17** [bio-ontology-research-group/mowl#63]
### Describe the bug

from mowl.nn import ELEModule
from mowl.base_models.elmodel import EmbeddingELModel

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
Cell In[1], line 1
----> 1 from mowl.nn import ELEModule
      2 from mowl.base_models.elmodel import EmbeddingELModel

ImportError: cannot import name 'ELEModule' from 'mowl.nn' 

also tried: 

from mowl.models.elembeddings.module import ELEModule
from mowl.base_models.elmodel import EmbeddingELModel

ImportError: Attempt to create Java package 'org' without jvm

### How to reproduce

from mowl.nn import ELEModule
from mowl.base_models.elmodel import EmbeddingELModel

#also tried

from mowl.models.elembeddings.module import ELEModule
from mowl.base_models.elmodel import EmbeddingELModel

### Environment

Python (using Pycharm)
mOWL version 0.2.1

**Comment by ferzcam** [comment]
Hi. Thanks for opening this issue. According to the code you shared, it seems the line 1 is `from mowl.nn import ELEModule`. Is that right? If so, the problem could be that lines `import mowl` and `mowl.init_jvm("5g")` are missing. Would you please make sure you have run those lines?

**Comment by ferzcam** [comment]
> Hi. Thanks for opening this issue. According to the code you shared, it seems the line 1 is `from mowl.nn import ELEModule`. Is that right? If so, the problem could be that lines `import mowl` and `mowl.init_jvm("5g")` are missing. Would you please make sure you have run those lines?

The code should look like this:
```
import mowl
mowl.init_jvm("10g")
from mowl.nn import ELEmModule
```

**Comment by Mhaller17** [comment]
Thank you! That seemed to fix the issue
