### ISSUE TITLE
HTTPError when using builtin datasets

### ISSUE THREAD

**Issue by filipkro** [bio-ontology-research-group/mowl#65]
### Describe the bug

Hi,
When trying to your your demo code for the builtin datasets I get, eg, the following error

```
HTTPError: 403 Client Error: Forbidden for url: https://bio2vec.cbrc.kaust.edu.sa/data/mowl/ppi_yeast_slim.tar.gz
```
I get the same trying to `wget` the tar file

### How to reproduce

```{python}
import mowl
mowl.init_jvm("5g")
from mowl.datasets.builtin import PPIYeastSlimDataset
ds = PPIYeastSlimDataset()
train_ontology = ds.ontology
valid_ontology = ds.validation
test_ontology = ds.testing
```

### Environment

Python 3.10.12
pip installed mowl-borg version 0.3.0

**Comment by coolmaksat** [comment]
Hi, thank you for reporting. It should work now.

**Comment by filipkro** [comment]
Thanks, it works!
