### ISSUE TITLE
setup.py Error While Building from Source

### ISSUE THREAD

**Issue by 20Bolin** [bio-ontology-research-group/mowl#76]
### Describe the bug

Hi, I was following the tutorial here https://pypi.org/project/mowl-borg/ to set up mowl. When I tried to build mowl from source, I followed the commands here:

git clone https://github.com/bio-ontology-research-group/mowl.git

cd mowl

conda env create -f envs/environment_3_8.yml
conda activate mowl

./build_jars.sh

python setup.py install

But at the last step "python setup.py install", it raised an error shown as in the screenshot:
<img width="947" alt="nimport_error" src="https://github.com/bio-ontology-research-group/mowl/assets/120567872/8889ed60-ca7a-4e62-9517-2ddd0c46fb7f">

There is a nimport in the first line of module.py, which is supposed to be import. However, I could not manually modify the code and run "python setup.py install" again. Because everytime I ran "python setup.py install", the command generated the module.py again and rewrote the old one so that in the new module.py, it is still nimport.

### How to reproduce

git clone https://github.com/bio-ontology-research-group/mowl.git

cd mowl

conda env create -f envs/environment_3_8.yml
conda activate mowl

./build_jars.sh

python setup.py install

### Environment

Windows 10
Python version 3.12.1
JDK version 11.0.22

**Comment by ferzcam** [comment]
Hello! Thank you for reporting this. Actually, this was solved but it was in the `develop` branch. I merged to the `main` branch and following the updated `README` you can now install with `pip install git+https://github.com/bio-ontology-research-group/mowl`. There is no need to build the `jars` anymore as they are included in the repository. I will close this issue but feel free to reopen it if you face other issues. 
Also, if you want to install from your local repository, you can do `pip install .`

**Comment by 20Bolin** [comment]
Hi, thanks for your quick reply and help! I would suggest you also make correction to the documentation https://mowl.readthedocs.io/en/latest/install/index.html and the pypi documentation https://pypi.org/project/mowl-borg/ to avoid confusion!
